name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['swift:5.9', 'swift:5.10', 'swift:6.0']
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --parallel --enable-code-coverage
